 ;ADDITION  
; MNEMONIC DESTINATION , SOURCE

DATA SEGMENT
     N1 DD 12345678H
     N2 DD 0AABBCCDDH
     N3 DD ?
     N4 DB ?
DATA ENDS

CODE    SEGMENT
        ASSUME CS:CODE DS:DATA
START:  MOV AX,DATA         ;DATA DECLARED IN DATA SEGMENT IS MOVED TO AX
        MOV DS,AX           ;DIRECTLY CANT BE LOADED TO DS REGISTER 
        
                            ;POINTER DECLARED AND INTIALISED BY THIS INSTRUCTIOINS      
        MOV SI,OFFSET N1    ;SI CAN BE USED AS POINTER NOW FOR N1 VARIABLE --5678
        MOV DI,OFFSET N2    ;DI CAN BE USED AS POINTER NOW FOR N2 VARIABLE --CCDD
        MOV BX,OFFSET N3    ;BX CAN BE USED AS POINTER NOW FOR N3 VARIABLE   ____
        MOV CL,00H          ;WE INITIALIZE CL AS CARRY STORAGE REGISTER 
        
        MOV AX,[SI]         ;AX- 5678
        ADD AX,[DI]         ;5678 + 0CCDD
        MOV [BX],AX         ;TRANSFER LOWER WORD OF N3
        
        MOV AX,[SI+2]       ;MOVE SI + 2BYTE TO AX (UPPER WORD)--1234
        ADC AX,[DI+2]       ;ADD AX + DI INCREMENTED 2 BYTE   -- 1234+AABB
        JNC L1              ;JUMP TO L1IF NO CARRY
        INC CL              ;INCREMENT CARRY REGISTER BY 1
        
L1:     MOV [BX+2],AX       ;TRANSFERING UPPERWORD AFTER ADC INSTRUCTION IN BX+2BYTE LOCATION
        MOV N4,CL
        
        MOV AX,4C00H
        INT 21H

CODE    ENDS                                   
        END START

        

        
      ; 1234 5678 H
      ; AABB CCDD H  